### ISSUE TITLE
Run rustfmt on the code

### ISSUE THREAD

**Issue by tomassedovic** [tomassedovic/roguelike-tutorial#10]
Making sure the code follows the community standards should make it easier on everyone. Run this and fix the issues it finds:

https://github.com/rust-lang-nursery/rustfmt

**Comment by iszla** [comment]
I have rustfmt running when I code, so I could do this one. It is actually causing some issue with my other PRs haha need to save differently to not have the formatter run. Should I do it with default settings or do you have a `rustfmt.toml` you would like to use?

**Comment by tomassedovic** [comment]
Default settings are just fine. I'm using them in my game and I've no strong reason to deviate.

If you do do that, could you please add an empty `rustfmt.toml` as well? An empty one will use the default setting, but it will indicate to other people and tools that we do use it:

https://www.reddit.com/r/rust/comments/9jl6a9/pro_tip_if_you_use_cargo_fmtrustfmt_use_a/
