### ISSUE TITLE
Simplify the drawing code?

### ISSUE THREAD

**Issue by tomassedovic** [tomassedovic/roguelike-tutorial#16]
Right now we need to clear all objects manually by calling `Object.clear` and when we forget to update something, it can stay on the screen indefinitely.

Since all of this is going through opengl anyway, we might as well just clear the game console and draw it all on every update. That result in less code and I doubt it would mean any difference performance-wise. (and if so, let's just add a note to that effect)

**Comment by iszla** [comment]
I guess this would be resolved once #43 is ready

**Comment by tomassedovic** [comment]
Fixed via #43

**Comment by tomassedovic** [comment]
Thanks again @iszla \o/
