### ISSUE TITLE
Tutorial fails to compile

### ISSUE THREAD

**Issue by anmej** [tomassedovic/roguelike-tutorial#19]
I'm attempting to compile with rustc 1.12.1 stable, on Ubuntu Linux, it fails when compiling tcod-sys v4.0.1.

**Comment by tomassedovic** [comment]
Hi! I've tried it with 1.12.1 (on Fedora but that shouldn't matter) and it compiled all right. Did you install the dependencies listed here?

https://github.com/tomassedovic/tcod-rs#building-on-linux

Could you also paste the error you're seeing when trying to compile?

**Comment by anmej** [comment]
I tried now on a different computer and it works fine. Probably didn't have the dependencies installed where it failed. I'll check later.

**Comment by anmej** [comment]
All works fine after dependencies are installed.

**Comment by tomassedovic** [comment]
Glad to hear that! Do you think there's something I can improve for the future readers? Maybe I should explicitly note that you'll need the dependencies from the tutorial?

**Comment by anmej** [comment]
Yes, noting the dependencies in the tutorial will be helpful, as some people will download it without checking the tcod-rs repository first

BTW, is the tutorial complete?

**Comment by tomassedovic** [comment]
Good point. The tutorial links to the dependencies page, but it's not obvious. I wish we didn't need the non-rust dependencies but libtcod uses them. Oh well.

And yes, the tutorial is complete. It covers all the sections that the original does and at the end you'll have a full game. That said, there's always more we could do. If you're interested, I've put some ideas in the issues page :-)

https://github.com/tomassedovic/roguelike-tutorial/issues

**Comment by anmej** [comment]
If the tutorial is done, you should, IMO, write a post about it on /r/rust, r/rust_gamedev, user.rust-lang etc. It deserves attention and comments.
