### ISSUE TITLE
Document how to run the binaries in this repo

### ISSUE THREAD

**Issue by tomassedovic** [tomassedovic/roguelike-tutorial#20]
Since they depend on the dynamic libtcod library, the examples here need to be run with `cargo run --bin ...` or `LD_LIBRARY_PATH`.

I thought I documented this but apparently not.

**Comment by iszla** [comment]
Should I make a PR to add this to the readme maybe?

**Comment by tomassedovic** [comment]
If you please, that would be fantastic, thanks! Any of the issues here are up for grabs if you're up for it!
