### ISSUE TITLE
Github pages not updated to reflect newest code

### ISSUE THREAD

**Issue by mipli** [tomassedovic/roguelike-tutorial#27]
Was about to write a PR to update the code to use `serde` instad of `rustc-serialize` when I saw that you had already done so. But the text, and examples, here https://tomassedovic.github.io/roguelike-tutorial/part-10-menu-saving.html have not been updated to show the newest version.

**Comment by tomassedovic** [comment]
Oh, thanks for letting me know!

I've been quite busy lately, but I'll try to merge the open pull requests soon and rebuild the website.

**Comment by thehornist** [comment]
Hey just wanted to let you know that the code is easy enough rework with serde but still would be awesome if it were documented by you. Also it would be super useful if on the tcod-rs repo/documentation it was more clear how to use the serialization feature. Thanks for doing the work that you've done thus far!

**Comment by tomassedovic** [comment]
Sorry for the massive delay and thanks for your patience and kind words!

The published tutorial now has the freshest code off the repo. Here's the serde section:

http://tomassedovic.github.io/roguelike-tutorial/part-10-menu-saving.html#_saving_and_loading

**Comment by tomassedovic** [comment]
@thehornist I've got very little time to devote to this now but if you submit a pull request against tcod, I'll be happy to take a look and merge it (though as evidenced here, even that may take a long time, sorry :-( )
