### ISSUE TITLE
Doesn't show console on Mac OS (step 1)

### ISSUE THREAD

**Issue by sardaukar** [tomassedovic/roguelike-tutorial#3]
I guess because libtcod is no longer supported on Mac OS. I tried running [another tutorial] that mentions fixing libtcod, but one of the files mentioned is a 404 by now.

[another tutorial]: http://jaredonline.svbtle.com/roguelike-tutorial-in-rust-part-1

Do you happen to know of a recent fix for Mac OS?

I also tried on Linux, but my AMD graphics card is too recent, and X segfaults all the time. Screw computers tonight :|

**Comment by tomassedovic** [comment]
:-(

Unfortunately, I don't have a Mac, but tcod-rs ships with a copy of libtcod that does have the files from the tutorial you linked. And we have a CI that tests each commit on OSX, Windows and Linux:

https://travis-ci.org/tomassedovic/tcod-rs/jobs/111536255

Can you please send me the steps you did and Cargo's output? It may be something I've seen before. 

I've also recently changed the way we build libtcod and it's possible I made a mistake somewhere so could you try tcod-rs "0.8.1"? That has the older build script and I know it worked for people on the Mac.

**Comment by sardaukar** [comment]
Well, I managed to fix my X11 segfaults, so screw Mac OS :D thanks for the help!

**Comment by tomassedovic** [comment]
Ok, cool :-). Although if you ever do want to spend the time & effort to capture the cargo output, I'll definitely look at it and see if we have something to fix.
