### ISSUE TITLE
Update to Rust 2018

### ISSUE THREAD

**Issue by tomassedovic** [tomassedovic/roguelike-tutorial#39]
We can remove `extern crate` and replace usages like: `Object { x: x, y: y, char: char, color: color }` with ` Object { x, y, char, color }` now.

**Comment by iszla** [comment]
Fixed in #52 not 100% sure if I got all cases.

**Comment by tomassedovic** [comment]
Yeah, that's kind of hard to verify. But it's much better now :-). Closing, thanks!
