### ISSUE TITLE
Update the code listings to match the formatting in the `.rs` files

### ISSUE THREAD

**Issue by tomassedovic** [tomassedovic/roguelike-tutorial#48]
With #46 all the files in `bin/` are now processed by `cargo fmt`.

But the code in the tutorial text is not. We should make sure they're in sync.

**Comment by iszla** [comment]
I have started going through all the text now, and I noticed this using statement `use tcod::colors::{self, Colors}`
Should it be like that, so colors are accessed with `color::WHITE` or should the import be changed to `use tcod::colors::*` so the color could be used with it's constant directly?

I am also removing all the `extern crate` lines as they are not needed anymore, and updated the object creation to `Object { x, y, char, color }` since the arguments are named the same.

**Comment by tomassedovic** [comment]
I prefer `color::WHITE` a little, but it's mostly a stylistic choice.

As for the latter, there's another issue for that: https://github.com/tomassedovic/roguelike-tutorial/issues/39

It'd be good to set the edition in `Cargo.toml` to 2018 if you're removing `extern crate` too.

**Comment by iszla** [comment]
I am noticing two types of comments, regular comments `//` and a type I have not seen before `*/`. Not a super important topic but I am curious about it since I have not seen this style before and I can not find any documentation on it.

Should I change them, or do they have some special meaning?

**Comment by tomassedovic** [comment]
I've tried to look for literal `*/` but could not find any. Do you mean comments that start with three slashes (`///`) insead of two (`//`)? If so, then yes, please keep them.

The triple-slashes indicate documentation comments. When you run `rustdoc` / `cargo doc` on the crate, they will turn into descriptions in the generated docs.

Here's some more info:
https://doc.rust-lang.org/1.30.0/book/second-edition/ch14-02-publishing-to-crates-io.html
https://doc.rust-lang.org/rust-by-example/meta/doc.html

Compare this tcod-rs file:
https://github.com/tomassedovic/tcod-rs/blob/master/src/console.rs

With the generated docs:
http://tomassedovic.github.io/tcod-rs/tcod/console/index.html

The whole Rust standard library reference is written that way too:
https://doc.rust-lang.org/std/

Might be worth adding a sentence or two when they're introduced.

**Comment by iszla** [comment]
My bad, the triple slash is normal, my editor ligatures are apparently not. Disabling them turned the `*/` comments into `///`
