### ISSUE TITLE
Wrong code snippet at the beginning of the Part 10

### ISSUE THREAD

**Issue by saintech** [tomassedovic/roguelike-tutorial#58]
https://github.com/tomassedovic/roguelike-tutorial/blob/0827995d623c4b687cea9579ba39aaa89f82118c/doc/part-10-menu-saving.adoc#L68-L69

Fix:

> ...
> For example the FoV map code now looks like this:
>
> ```diff
> for y in 0..MAP_HEIGHT {
>     for x in 0..MAP_WIDTH {
>         tcod.fov.set(
>             x,
>             y,
> -            !map[x as usize][y as usize].block_sight,
> -            !map[x as usize][y as usize].blocked,
> +            !game.map[x as usize][y as usize].block_sight,
> +            !game.map[x as usize][y as usize].blocked,
>         );
>     }
> }
> ```
> ...

<sub><sup>P.S. Thank you so much for the wonderful tutorial, it is very exciting to learn Rust with this.</sup></sub>

**Comment by tomassedovic** [comment]
Good catch, thanks!

There are several things like that in the text. Given the repetition and the difficulty to keep this in sync manually, I'm working on a way to generate the code from the tutorial itself:

https://github.com/tomassedovic/roguelike-tutorial/pull/53

It's a slow work, but it should fix all the current and future issues like this as there will be a single source of truth.

**Comment by tomassedovic** [comment]
Should be fixed now. The tutorial still uses `!map` instead of `!game.map` but the function it's in gets passed `map` directly.
