### ISSUE TITLE
Key printable '<' is never triggered

### ISSUE THREAD

**Issue by saintech** [tomassedovic/roguelike-tutorial#59]
**Rust tcod version** - 0.15.0
**OS** - Windows 10 64bit 1803 Build 17134.950

https://github.com/tomassedovic/roguelike-tutorial/blob/0827995d623c4b687cea9579ba39aaa89f82118c/doc/part-11-dungeon-progression.adoc#L43-L52

But this works fine:
```
(Key { printable: ',', .. }, true) => {
```
or
```
(Key { code: Text, .. }, true) if key.text() == "<" => {
```

Maybe it is mistake from original python tutorial, but it seems libtcod does not work this way.

**Comment by tomassedovic** [comment]
Thanks! I'll switch to `key.text()` (it's better with respect to non-English keyboard layouts.

**Comment by tomassedovic** [comment]
And sorry for the long wait!

**Comment by saintech** [comment]
No problems. If you are interested to look at one of the results of completing your tutorial - https://github.com/saintech/expt01

**Comment by tomassedovic** [comment]
That looks nice!
